// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  links: string;
  logo: string;
}
export const cssExports: CssExports;
export default cssExports;
